# Compose file made under the assumption that all service is running in the same network and expose the same port number
version: "3"
services:      
  microservice2:
    container_name: ${WSB_1_CONTAINER_NAME}
    build:
      context: ./${WSB_1_CONTAINER_NAME}
    volumes:
      - ./${WSB_1_CONTAINER_NAME}/${WSB_1_CONTAINER_NAME}/static:/home/www-data/app/static
      - ./${WSB_1_CONTAINER_NAME}/${WSB_1_CONTAINER_NAME}/api:/home/www-data/app/api
      - ./${WSB_1_CONTAINER_NAME}/${WSB_1_CONTAINER_NAME}/frontend:/home/www-data/app/frontend
      - ./${WSB_1_CONTAINER_NAME}/${WSB_1_CONTAINER_NAME}/${WSB_1_CONTAINER_NAME}:/home/www-data/app/${WSB_1_CONTAINER_NAME}
      - ./${WSB_1_CONTAINER_NAME}/${WSB_1_CONTAINER_NAME}/templates:/home/www-data/app/templates
    environment:
      - NAME=${WSB_1_PRETTY_NAME}
      - APPNAME=${WSB_1_CONTAINER_NAME} 
      - SERVICE_PORT=${SERVICE_PORT}
    depends_on:
      - gateway
    restart: on-failure
  microservice3:
    container_name: ${LSP_2_CONTAINER_NAME}
    build:
      context: ./${LSP_2_CONTAINER_NAME}
    volumes:
      - ./${LSP_2_CONTAINER_NAME}/${LSP_2_CONTAINER_NAME}/static:/home/www-data/app/static
      - ./${LSP_2_CONTAINER_NAME}/${LSP_2_CONTAINER_NAME}/api:/home/www-data/app/api
      - ./${LSP_2_CONTAINER_NAME}/${LSP_2_CONTAINER_NAME}/frontend:/home/www-data/app/frontend
      - ./${LSP_2_CONTAINER_NAME}/${LSP_2_CONTAINER_NAME}/${LSP_2_CONTAINER_NAME}:/home/www-data/app/${LSP_2_CONTAINER_NAME}
      - ./${LSP_2_CONTAINER_NAME}/${LSP_2_CONTAINER_NAME}/templates:/home/www-data/app/templates
      - ./${LSP_2_CONTAINER_NAME}/gunicorn:/etc/gunicorn
    environment:
      - NAME=${LSP_2_PRETTY_NAME}
      - APPNAME=${LSP_2_CONTAINER_NAME} 
      - SERVICE_PORT=${SERVICE_PORT}
    depends_on:
      - gateway
    restart: on-failure
  microservice1:
    container_name: enroll
    build:
      context: ./backend
    volumes:
      - ./backend/UniService/static:/home/www-data/app/static
      - ./backend/UniService/api:/home/www-data/app/api
      - ./backend/UniService/frontend:/home/www-data/app/frontend
      - ./backend/UniService/accounts:/home/www-data/app/accounts
      - ./backend/UniService/UniService:/home/www-data/app/UniService
      - ./backend/UniService/templates:/home/www-data/app/templates
      - ./backend/gunicorn:/etc/gunicorn
    environment:
      - NAME='UniService'
      - APPNAME=UniService
      - PROJECTPATH=/home/www-data/app
      - PIDFILE=/tmp/gunicorn.pid
      - DB_NAME=serviceuni
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=aws.connect.psdb.cloud
      - DB_PORT=3306
      - MYSQL_ATTR_SSL_CA=${MYSQL_ATTR_SSL_CA}
    depends_on:
      - gateway
    restart: on-failure
  gateway:
    container_name: gateway
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./static:/var/www/static
    environment:
      - WSB_1_CONTAINER_NAME=${WSB_1_CONTAINER_NAME}
      - LSP_2_CONTAINER_NAME=${LSP_2_CONTAINER_NAME}
      - ESP_4_CONTAINER_NAME=${ESP_4_CONTAINER_NAME}
      - SERVICE_PORT=${SERVICE_PORT}
      - SECRET_KEY=${SECRET_KEY}
    restart: on-failure
